nama = input("masukkan nama : ")
tgl = input("masukkan tanggal lahir : ")
hobi = input("masukkan hobi : ")
pemisah = tgl.split("")
print("tanggal {pemisah[0]}, bulan {pemisah[1]}, tahun {pemisah[2]}")